### PR TITLE
Move older/stub docs to "inactive"

### PR DESCRIPTION
**Pull request by manez**
**GitHub Issue**: #1352

# What does this Pull Request do?

Moves a number of stub or out-of-date documentation pages to an `inactive` folder, and deletes one blank file.

# How should this be tested?

Verify that all files are in a new folder, "inactive."

# Additional Notes:
Some of these are stubs that have notes for what questions to answer when building a full page later, which seemed useful. Some are older 'CLAW" docs that may or may not be accurate and would need some love before being published with our official docs again, some cover ground that is covered better by newer docs, and the things formerly in the `migration` folder I just didn't know what to do with, but I don't think they belong in the current docs without explanation, so off to `inactive` they go.

I considered `deprecated` for the new folder, but I don't think that reflects the status of all of the files that I'm proposing to move, and I didn't think it was worth making multiple new folders.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by manez** [comment]
@Islandora/8-x-committers I think this just needs a quick look by some one who is not @dannylamb (because he can't merge his co-worker's PR) and it'll check off a milestone task 😄

**Comment by whikloj** [comment]
I can merge this, but there are still other files that are not linked to and are not in the inactive folder. 
For example: http://islandora.github.io/documentation/contributing/readme_template/

**Comment by manez** [comment]
Hrm. The readme template is sort of a special case and I'll give that some thought. And go back through and clear up anything else I missed.

**Comment by whikloj** [comment]
Here is the listing when I built this PR.
```
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - alpaca/alpaca-technical-stack.md
  - contributing/hacking-on-islandora.md
  - contributing/readme_template.md
  - inactive/derivatives.md
  - inactive/different_from_7x.md
  - inactive/fedora-namespace-predicates.md
  - inactive/fedora-rdf.md
  - inactive/getting-started-with-islandora-claw.md
  - inactive/intro-to-8.md
  - inactive/islandora-namespace-predicates.md
  - inactive/migration.md
  - inactive/mvp_doc.md
  - inactive/structure.md
  - islandora/drupal-bundle-configurations.md
  - technical-documentation/checking-coding-standards.md
  - technical-documentation/drupal-project.md
  - technical-documentation/resizing_vm.md
  - user-documentation/intro-to-ld-for-islandora-8.md
  - user-documentation/versioning.md 
WARNING -  Documentation file 'inactive/different_from_7x.md' contains a link to 'migration/migration.md' which is not found in the documentation files. 
WARNING -  Documentation file 'user-documentation/collections.md' contains a link to 'assets/collections_admin_content_button.png' which is not found in the documentation files. 
```
The ones _not_ in the inactive directory were the ones I was focused on.

**Comment by manez** [comment]
@whikloj looks like most of those I got with links in https://github.com/Islandora/documentation/pull/1419 

Which leaves just the readme template? I would argue that it's not useful within the built docs, but we still need it for a reference, so I could move it somewhere else to get it out of these results, but I don't think it should be linked in the docs and I don't think it' "inactive," so I'd rather leave it be. Thoughts?

**Comment by whikloj** [comment]
@manez you are correct, my master branch was behind and once I updated it I now see only two not files not linked and not in `inactive`.
```
> mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /sw/var/www/DAM2/documentation/site 
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - contributing/readme_template.md
  - inactive/derivatives.md
  - inactive/different_from_7x.md
  - inactive/fedora-namespace-predicates.md
  - inactive/fedora-rdf.md
  - inactive/getting-started-with-islandora-claw.md
  - inactive/intro-to-8.md
  - inactive/islandora-namespace-predicates.md
  - inactive/migration.md
  - inactive/mvp_doc.md
  - inactive/structure.md
  - technical-documentation/checking-coding-standards.md 
```
You have addressed the question of the `readme_template.md`, so I guess the only question is `checking-coding-standards.md`?

**Comment by manez** [comment]
Hrm. I linked that one, but it is clearly borked: https://islandora.github.io/documentation/checking-coding-standards.md

Checking...

**Comment by manez** [comment]
Missed the folders part of the url. Hopefully this fixes it and doesn't just pile conflicts into the PR...

**Review by whikloj — APPROVED** [review]
👍

**Pull request merged**
