### PR TITLE
Update advanced-search.md

### PR DESCRIPTION
**Pull request by edlington**
The word decedent means one who has died. Based on the context of the documentation the word you are looking for is descendant. I changed it in the documentation above. The only pratical implication is that I also changed the name of the filter in the documentation to field_descendant_of.

## Purpose / why

> _**Ensure the documentation is clear and uses words consistent with their meaning** - Restate the purpose/justification of this work and include links to any Issues or other discussions that are related to this work._

## What changes were made?

> _**References to decedent were changed to descendant** - State clearly the direct additions or modifications made in this pull request._

## Verification

> _**Search on descendant to see the changes that were made** - Document the details that help a reviewer verify the documentation._

## Interested Parties

> _**@Melissa Anez* - Name some folks who may be interested, if documentation related mention @Islandora/documentation, or, if unsure, @Islandora/8-x-committers_

---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Does this PR link to related [issues](https://github.com/Islandora/documentation/issues/)?
* [ ] Does the proposed documentation align with the [Islandora Documentation Style Guide](https://islandora.github.io/documentation/contributing/docs_style_guide/)?
* [ ] Are the changes accurate, useful, free of typos, etc?
* [ ] Does this PR update the _last updated on_ date on the documentation page?

> __Person merging__ should ensure the following
* [ ] Does mkdocs still build successfully? (This is indicated by TravisCI passing. To test locally, and see warnings, see [How To Build Documentation](https://islandora.github.io/documentation/technical-documentation/docs-build/).)
* [ ] If pages are renamed or removed, have all internal links to those pages been fixed?
* [ ] If pages are added, have they been linked to or placed in the menu?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
@edlington, would you be willing to recapture the first two screenshot pngs to reflect the correct working? Otherwise it looks good to me.

**Comment by edlington** [comment]
@seth-shaw-unlv Sure, I could grab those. I'm guessing you're asking me to do that once this update has been pulled into the sandbox?

**Comment by seth-shaw-unlv** [comment]
I suppose you could wait for the sandbox to include the latest commit. You could probably convince @dannylamb to get it in sooner rather than latter. Or you could spin up an isle_dc instance and do it there.

Failing that, I suppose we could just merge this as long as we leave an issue open to correct those later.

**Comment by edlington** [comment]
@seth-shaw-unlv Lemme take a look at my isle_dc instance tomorrow and see if I can get the screenshots taken. If for some reason it's not working for me I'll give you a shout.

**Comment by edlington** [comment]
Here's first screenshot:
Screenshot from 2021-06-28 10-03-21

**Comment by edlington** [comment]
@seth-shaw-unlv Initial screenshot is above. I'm having trouble figuring out how to get the descendant term to display in the index hierarchy list under Processor Settings. See attached screenshot. Do you know how I might get that to show up? Thank you!
Screenshot from 2021-06-28 11-06-11

**Comment by seth-shaw-unlv** [comment]
Something odd is happening here. It should at least show the provided Member Of field as an option.... I'm not sure what is happening here.

**Comment by edlington** [comment]
@seth-shaw-unlv Thanks for taking a look. Can you get Member Of field to show up under Processor Settings -> Index Hierarchy on your instance? If not, could there be a bug somewhere?

**Comment by seth-shaw-unlv** [comment]
I didn't add the field_descendant_of, but field_member_of showed up after I added it:
Screen Shot 2021-06-28 at 9 56 24 AM

**Review by manez — APPROVED** [review]

**Pull request merged**
