### PR TITLE
Added "make command not found" failure fix

### PR DESCRIPTION
**Pull request by mxMiles**
## Purpose / why

I skimmed the directions and got the error "make command not found". Others might, too.

## What changes were made?

Added description of error and the fix.

## Verification

I spell checked? 

## Interested Parties

@Islandora/documentation 
---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Does this PR link to related [issues](https://github.com/Islandora/documentation/issues/)?
* [ ] Does the proposed documentation align with the [Islandora Documentation Style Guide](https://islandora.github.io/documentation/contributing/docs_style_guide/)?
* [ ] Are the changes accurate, useful, free of typos, etc?
* [ ] Does this PR update the _last updated on_ date on the documentation page?

> __Person merging__ should ensure the following
* [ ] Does mkdocs still build successfully? (This is indicated by TravisCI passing. To test locally, and see warnings, see [How To Build Documentation](https://islandora.github.io/documentation/technical-documentation/docs-build/).)
* [ ] If pages are renamed or removed, have all internal links to those pages been fixed?
* [ ] If pages are added, have they been linked to or placed in the menu?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

### CODE REVIEW

**Comment by manez** [comment]
Thank you for this, @archivalGrysbok ! Alas, I'm afraid we have one small hoop to clear for first-time contributors: 

Before you set out to contribute code you will need to have completed a [Contributor License Agreement](http://islandora.ca/sites/default/files/islandora_cla.pdf) or be covered by a [Corporate Contributor Licencse Agreement](http://islandora.ca/sites/default/files/islandora_ccla.pdf). The signed copy of the license agreement should be sent to <mailto:community@islandora.ca>

This license is for your protection as a contributor as well as the protection of the Foundation and its users; it does not change your rights to use your own contributions for any other purpose.

**Comment by DonRichards** [comment]
@manez This submission isn't actual code (just documentation). Is it possible this could be an exception?

**Comment by manez** [comment]
@DonRichards per policy and practice at the IF, I'm afraid not. All contributions are treated equal in the eyes of the CLA. The Documentation Interest Group has this one in their sights and a volunteer to redo it, but it hasn't happened yet.

**Comment by ysuarez** [comment]
I just created PR #1995 to essentially recreate this PR (#1816) I am commenting on. Since we never got a CLA from the contributor after repeated attempts to contact them.

**Pull request closed without merging**
