### PR TITLE
Release notes??

### PR DESCRIPTION
**Pull request by elizoller**
## Purpose / why

An attempt to start documenting release notes.

## What changes were made?

 Add a release notes section

## Interested Parties

@Islandora/8-x-committers_

### CODE REVIEW

**Comment by dannylamb** [comment]
:bowing_man:

**Comment by seth-shaw-unlv** [comment]
Should the filename be 2.x instead of 8.x-2.x since we are going to do the semantic versioning change?

**Comment by seth-shaw-unlv** [comment]
Question: should we add a "you need to run update-db" to these release notes (for the media__field_file_size update), or can we assume that this is standard Drupal updating procedure and doesn't bear mentioning?

Also, perhaps this PR should be based on a branch of documentation rather than a fork, that way multiple individuals can contribute to the PR?

**Comment by elizoller** [comment]
I think it's worth adding. and yeah, a branch a bunch of people can contribute to makes sense to me. do i have permission to do that?

**Comment by seth-shaw-unlv** [comment]
_I think so..._ I do.

**Comment by dannylamb** [comment]
Both of you should.  If there's any issue pushing a branch, let me know.

**Comment by elizoller** [comment]
this is being closed and replaced with https://github.com/Islandora/documentation/pull/1789

**Pull request closed without merging**
