### PR TITLE
Adding links to Islandora Quick Lessons on Youtube in docs that align with the topics.

### PR DESCRIPTION
**Pull request by manez**
**GitHub Issue**: #1487 

# What does this Pull Request do?

Adds links to videos from the [Islandora Quick Lessons](https://www.youtube.com/playlist?list=PL4seFC7ELUtripxWi_2RIBKCWqI0uif93) that match up with topics in our docs. I used the tip formatting to make their addition consistent across different pages.

# How should this be tested?

Preview & review. The tip formatting won't show up outside of built docs, [like this](https://islandora.github.io/documentation/user-documentation/collections/)

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by manez** [comment]
@seth-shaw-unlv since you fell for my clever trap and merged that last one...

**Review by whikloj — APPROVED** [review]
👍

**Comment by whikloj** [comment]
Oops sorry @seth-shaw-unlv and @manez I had already pulled this down and was reviewing it. I'll leave the next one for you.

**Comment by manez** [comment]
No sweat! I'm just poking at people who seem to be around and in a merging mood today 😄

**Pull request merged**
