### PR TITLE
Update committers.md

### PR DESCRIPTION
**Pull request by dannylamb**
## Purpose / why

As is tradition, @manez shall merge this PR as her first act as a committer.

## What changes were made?

@manez has been added to the committers list

## Interested Parties

@manez

## Checklist

> __Pull-request reviewer__ should ensure the following

* [x] Does this PR link to related [issues](https://github.com/Islandora/documentation/issues/)? - No issue
* [x] Does the proposed documentation align with the [Islandora Documentation Style Guide](https://islandora.github.io/documentation/contributing/docs_style_guide/)?
* [x] Are the changes accurate, useful, free of typos, etc?

> __Person merging__ should ensure the following
* [x] Does mkdocs still build successfully? (This is indicated by TravisCI passing. To test locally, and see warnings, see [How To Build Documentation](https://islandora.github.io/documentation/technical-documentation/docs-build/).)
* [x] If pages are renamed or removed, have all internal links to those pages been fixed?
* [x] If pages are added, have they been linked to or placed in the menu?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

### CODE REVIEW

**Comment by manez** [comment]
Alas for tradition, I don't want my first act as a committer to violate our policies, so I can't merge a PR made by some one who works for the same organization that I do. Would another @Islandora/8-x-committers do me the honor?

**Comment by whikloj** [comment]
I'll do it, but I think @manez should at least approve her own inclusion.

**Review by manez — APPROVED** [review]
Yay!

**Comment by manez** [comment]
@whikloj So approved 😉

**Pull request merged**
