### PR TITLE
install-a-demo.md fixes

### PR DESCRIPTION
**Pull request by ysuarez**
## Purpose / why

I wanted to clean up the content of install-a-demo.md, including remove mentions of two demo types when now we only have one. Also to add a link to the new video installation tutorial. 

## What changes were made?

Added some grammar, content, spelling fixes to `install-a-demo.md`

## Interested Parties

* @Islandora/documentation
* @Islandora/committers

### Pull-request Reviewer
Pull-request reviewer should ensure the following:

* [ ] Does this PR link to related [issues](https://github.com/Islandora/documentation/issues/)?
* [ ] Does the proposed documentation align with the [Islandora Documentation Style Guide](https://islandora.github.io/documentation/contributing/docs_style_guide/)?
* [ ] Are the changes accurate, useful, free of typos, etc?

### Person Merging
The person merging should ensure the following:

* [ ] Does mkdocs still build successfully? (This is indicated by TravisCI passing. To test locally, and see warnings, see [How To Build Documentation](https://islandora.github.io/documentation/technical-documentation/docs-build/).)
* [ ] If pages are renamed or removed, have all internal links to those pages been fixed?
* [ ] If pages are added, have they been linked to or placed in the menu?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

### CODE REVIEW

**Review by rosiel — APPROVED** [review]

**Comment by rebeccapower** [comment]
It looks like with this merged my other additions weren't merged. I really don't understand how Github/commits/PRs/merging works so unsure how to resolve this. But my original PR was https://github.com/Islandora/documentation/pull/2227

Should I redo my changes and make a new PR? Or is it possible to still merge 2227?

**Comment by ysuarez** [comment]
@rebeccapower my apologies again. I thought you were done with you updated to that file.

I can guide you how to fix this on the command line with git if that is an approach you want to take, but we can work and learn together so you (or I) can fix this online via using github.com. I have a vague idea of how to do it on github.com, but need to do some googling before I could do the whole thing via github.com.

what do you prefer?

**Comment by seth-shaw-asu** [comment]
Yes, we can still merge #2227! I took the liberty of resolving a merge conflict, but it is ready for review and merging.

**Comment by rebeccapower** [comment]
@ysuarez no worries at all! I am still learning so there's bound to be confusion!

@seth-shaw-asu Thank you for this! I'm sure it'll come up in the next open tech call so we can get it all sorted then! 

If there's anything I can/should do before then with this please let me know!

**Pull request merged**
