### PR TITLE
#1761 Document Islandora Advanced Search

### LINKED ISSUE #1761: Document new Advanced Search module once merged
https://github.com/Islandora/islandora/pull/824 proposes to add new Advanced Search Module to Islandora Core. 

Once approved and merged, the module's comprehensive readme information should be added to the documentation (https://github.com/nigelgbanks/islandora/tree/8.x-1.x-advanced-search/modules/islandora_advanced_search).

@Islandora/documentation

### PR DESCRIPTION
**Pull request by manez**
## Purpose / why

Create a new page documenting how to configure new Advanced Search. Resolves #1761 

## What changes were made?

New .md, new screenshots in the assets folder, and new entry in mkdocs.yml to add the page to the tree.

## Verification

Review! This is mostly lifted from the great docs @nigelgbanks already made in the readme: https://github.com/nigelgbanks/islandora/blob/8.x-1.x-advanced-search/modules/islandora_advanced_search/README.md, with some changes to make it a docs page instead of a readme and to fit the style guide.

## Interested Parties

@Islandora/documentation and @nigelgbanks 

---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Does this PR link to related [issues](https://github.com/Islandora/documentation/issues/)?
* [ ] Does the proposed documentation align with the [Islandora Documentation Style Guide](https://islandora.github.io/documentation/contributing/docs_style_guide/)?
* [ ] Are the changes accurate, useful, free of typos, etc?
* [ ] Does this PR update the _last updated on_ date on the documentation page?

> __Person merging__ should ensure the following
* [ ] Does mkdocs still build successfully? (This is indicated by TravisCI passing. To test locally, and see warnings, see [How To Build Documentation](https://islandora.github.io/documentation/technical-documentation/docs-build/).)
* [ ] If pages are renamed or removed, have all internal links to those pages been fixed?
* [ ] If pages are added, have they been linked to or placed in the menu?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

### CODE REVIEW

**Comment by rosiel** [comment]
I tested locally. It can't find the images, I think you might need ../../assets?

**Comment by manez** [comment]
Gave that a try! They are now all broken in my repo, but if they built in the real docs, then 👍

**Comment by eldonquijote** [comment]
I think that's one .. too many, you need to go one level up and then one down into the assets folder: 
`../assets/`

**Comment by manez** [comment]
That does look better in the browser view

**Comment by rosiel** [comment]
Action gifs! Nice!

**Pull request merged**
