### PR TITLE
Include a recipe for multi-file media

### PR DESCRIPTION
**Pull request by rosiel**
## Purpose / why

Multi-file has not been documented

## What changes were made?

Provide short recipe / how to configure.

## Verification

try...it?

## Interested Parties

@manez @eldonquijote 

---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Does this PR link to related [issues](https://github.com/Islandora/documentation/issues/)?
* [ ] Does the proposed documentation align with the [Islandora Documentation Style Guide](https://islandora.github.io/documentation/contributing/docs_style_guide/)?
* [ ] Are the changes accurate, useful, free of typos, etc?
* [ ] Does this PR update the _last updated on_ date on the documentation page?

> __Person merging__ should ensure the following
* [ ] Does mkdocs still build successfully? (This is indicated by TravisCI passing. To test locally, and see warnings, see [How To Build Documentation](https://islandora.github.io/documentation/technical-documentation/docs-build/).)
* [ ] If pages are renamed or removed, have all internal links to those pages been fixed?
* [ ] If pages are added, have they been linked to or placed in the menu?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

### CODE REVIEW

**Comment by eldonquijote** [comment]
I've tried to configure a multi-file media type on the public sandbox: https://future.islandora.ca/admin/structure/media/manage/image_multi_test?destination=/admin/structure/media. This test media type has two additional fields that can store images. Now I get stuck at configuring the contexts. Do I need to set up a new context, or edit the existing "image derivatives" context in my example?

**Comment by ajstanley** [comment]
@eldonquijote  You need to create an Action, then a new context.  
[Here's](https://youtu.be/3U6tBvD8oJY ) a quick video walkthrough

**Comment by eldonquijote** [comment]
Thank you, Alan, that is very helpful! I had in fact already set up an Action, but the sandbox doesn't offer the additional Media type fields I created as an option for Destination Field names. It only shows field_media_file, field_media_audio_file, field_media_video_file.

**Comment by eldonquijote** [comment]
Okay, found the issue: I had added new _Image_ type fields to my custom media type. They don't show up as Destination Fields when creating an Action based on "Generate an Image Derivative for Media Attachment". I added a new field of type _File_, and it is available as a Destination Field for the Action.

**Comment by eldonquijote** [comment]
Still can't get this to work, the sandbox gives me the error message "Symfony\Component\HttpKernel\Exception\BadRequestHttpException: Invalid file extension. Valid types are jpeg jpg in Drupal\islandora\MediaSource\MediaSourceService->putToMedia() (line 362 of /var/www/drupal/web/modules/contrib/islandora/src/MediaSource/MediaSourceService.php)." The file I attached to the Media entity is a JPEG file with a .jpg extension. Any idea what could be the problem?

**Comment by ajstanley** [comment]
@eldonquijote Looks like you forgot to rename the destination file in your [Action](https://future.islandora.ca/admin/config/system/actions/configure/generate_a_derivative_file_for_media_attachment?destination=/admin/config/system/actions) .
I took the liberty of changing [date:custom:Y]-[date:custom:m]/[media:mid].bin to [date:custom:Y]-[date:custom:m]/[media:mid].jpg and it works (for me) like it's meant to now.  I haven't test the context yet - I invoked the Action from the Media tab of the Content page.

**Comment by eldonquijote** [comment]
@ajstanley Thank you! And sorry for my oversight, I seem to have inherited my custom action from the wrong preset action (Generate derivative _file_ instead of _image_). It works now on the sandbox, including the context triggering the action!

**Comment by rosiel** [comment]
Thanks @eldonquijote and @ajstanley for the improvements!

**Pull request merged**
