### PR TITLE
Update committers.md

### PR DESCRIPTION
**Pull request by manez**
## Purpose / why

Adds our newest Committer to the list!

## What changes were made?

Added @dflitner to the canonical list of Islandora 8 Committers 😄 

## Verification

A simple preview and review to verify that the info is correct and everything is spelled correctly.

## Interested Parties

@dflitner want to make this your first merge?

---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Does this PR link to related [issues](https://github.com/Islandora/documentation/issues/)?
* [ ] Does the proposed documentation align with the [Islandora Documentation Style Guide](https://islandora.github.io/documentation/contributing/docs_style_guide/)?
* [ ] Are the changes accurate, useful, free of typos, etc?

> __Person merging__ should ensure the following
* [ ] Does mkdocs still build successfully? (This is indicated by TravisCI passing. To test locally, and see warnings, see [How To Build Documentation](https://islandora.github.io/documentation/technical-documentation/docs-build/).)
* [ ] If pages are renamed or removed, have all internal links to those pages been fixed?
* [ ] If pages are added, have they been linked to or placed in the menu?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

### CODE REVIEW

**Comment by dflitner** [comment]
Spelling and info is accurate. Not sure if it's ok for me to do both the approving review and merge?

**Comment by seth-shaw-unlv** [comment]
@dflitner, yes, you get to approve _and_ merge.

**Review by dflitner — APPROVED** [review]
Info looks accurate :)

**Comment by manez** [comment]
And with the magic of auto-building docs, it's already up here: https://islandora.github.io/documentation/contributing/committers/ 🥳

**Pull request merged**
