### PR TITLE
Describe why we make media.

### PR DESCRIPTION
**Pull request by rosiel**
## Purpose / why

The tutorial glossed over how we're doing things very differently than Drupal. i wanted to point that out, to respect the reader's understanding of Drupal (and that the instructions were doing something very roundabout)

## What changes were made?

an lobster-emoji'd admonition talking about how "we attach files via media attached to nodes."

## Verification

Does it jive, and does it display right?

## Interested Parties

@manez @eldonquijote 

---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Does this PR link to related [issues](https://github.com/Islandora/documentation/issues/)?
* [ ] Does the proposed documentation align with the [Islandora Documentation Style Guide](https://islandora.github.io/documentation/contributing/docs_style_guide/)?
* [ ] Are the changes accurate, useful, free of typos, etc?
* [ ] Does this PR update the _last updated on_ date on the documentation page?

> __Person merging__ should ensure the following
* [ ] Does mkdocs still build successfully? (This is indicated by TravisCI passing. To test locally, and see warnings, see [How To Build Documentation](https://islandora.github.io/documentation/technical-documentation/docs-build/).)
* [ ] If pages are renamed or removed, have all internal links to those pages been fixed?
* [ ] If pages are added, have they been linked to or placed in the menu?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
I would say that the move from files to Media is a Drupal community move. This allows media resources be more easily reused in multiple areas of a site. 

What is peculiar to Islandora is that we have Media reference particular nodes rather than having the content entities reference the media (although the need for this Islandora-ism has recently been called into question).

**Comment by manez** [comment]
@rosiel can you add a `_last updated on DD-MM-YYYY_` to the top of the page, just under the heading?

@seth-shaw-unlv does your clarification need to be reflected in the text? If not, I'd like to merge this once the date is added.

**Comment by rosiel** [comment]
I think that what you described @seth-shaw-unlv  is the technical implementation of a concept, which we have in Islandora, which is that "media belong to nodes". I was trying to avoid concepts in this tutorial, but I think this is important. I hope it's okay that I left out "we put the entity relationship field on the media pointing to the node rather than the node pointing to the media" at a tutorial at this level. Also, "the drupal concept of media is reusable files, but what islandora does with media is both a departure from that concept and an extension on that concept because while in order to properly be 'islandora', a media should belong to a node, but *also* it can be re-used anywhere on the site" is something that should probably be said but on the conceptual page about nodes and/or media, not this tutorial.

**Review by manez — APPROVED** [review]
Looks good in the build. 

I think @seth-shaw-unlv is on vacation this week. Since we can always go back and make changes later if there _are_ points to clarify, I'm going to go ahead and merge for now.

**Comment by seth-shaw-unlv** [comment]
Sorry I missed this. I think you did a good job, @rosiel. 👍

**Pull request merged**
