### PR TITLE
Update Datastreams docs to reflect multiple Media Use tags

### PR DESCRIPTION
**Pull request by mjordan**
**GitHub Issue**: #1205

# What does this Pull Request do?

Updates "Datastreams" docs to include a new screenshot and explanation of the Media Use vocabulary. See it [here](https://github.com/mjordan/CLAW/blob/issue-1205/docs/user-documentation/media.md).

# What's new?

Updated documentation.

# How should this be tested?

Visit [my branch](https://github.com/mjordan/CLAW/blob/issue-1205/docs/user-documentation/media.md) and take a look.

# Interested parties
@manez, @Islandora-CLAW/committers

### CODE REVIEW

**Review by manez — APPROVED** [review]
The changes and the new screenshot look good. Approving what's new, but I would also suggest that on line 43, "For more information on how to set configure derivatives, see the section on context" be changed to include a link to the context doc.

**Comment by rosiel** [comment]
Great improvement thanks @mjordan

**Comment by mjordan** [comment]
I'll make that change @manez.

**Comment by mjordan** [comment]
Also, the .md filename is 'datastreams'; should we rename this to 'media.md'?

**Comment by dannylamb** [comment]
@mjordan Yeah probably.  Just be sure to update its entry in the mkdocs.yml file if you do so.

**Review by dannylamb — APPROVED** [review]
:+1:

**Pull request merged**
