### PR TITLE
Add running phpcs to the technical docs

### PR DESCRIPTION
**Pull request by mjordan**
**GitHub Issue**: #1182 

This PR incorporates feedback from #1183 and replaces that PR.

# What does this Pull Request do?

Adds a new page to the technical documentation describing how to check your coding style.

# What's new?
A new .md file in the technical docuemenation directory.

# How should this be tested?
 Review it for clarity and completeness, and consistency with other docs.

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by rosiel** [comment]
Tried it, and got `ERROR: the "/vendor/drupal/coder/coder_sniffer/Drupal" coding standard is not installed. The installed coding standards are PSR12, Squiz, Zend, MySource, PSR2, PSR1 and PEAR`. 

I think in the second example, `standard=/vendor/drupal/coder/coder_sniffer/Drupal` should be `standard=../vendor/drupal/coder/coder_sniffer/Drupal` (I know, you say later "the path can be relative" but it's unlikely that anyone has a /vendor directory.)

**Comment by rosiel** [comment]
Also, and this is maybe an open question for the community, do we enforce line length restrictions? in CONTRIBUTING.md and README.md files, we often exceed 80 chars. Are .md files a "habitual exclusion" in our practice?

**Comment by mjordan** [comment]
@roseil when you say

> Tried it, and got ERROR: the "/vendor/drupal/coder/coder_sniffer/Drupal" coding standard is not installed. The installed coding standards are PSR12, Squiz, Zend, MySource, PSR2, PSR1 and PEAR.

which command did you try?

**Comment by mjordan** [comment]
No idea about length of lines in .md files, others should respond to that one.

**Comment by jonathangreen** [comment]
For our travis testing we are excluding `.md` files.
https://github.com/Islandora-CLAW/CLAW/blob/master/.scripts/travis_scripts.sh#L16

**Comment by dannylamb** [comment]
The full command I usually run is (from the `web` directory):

```
../vendor/bin/phpcs --standard=../vendor/drupal/coder/coder_sniffer/Drupal --ignore=*.md --extensions=php,module,inc,install,test,profile,theme,css,info modules/contrib/my_module
```

**Comment by mjordan** [comment]
#1220 replaces this PR.

**Pull request closed without merging**
