### PR TITLE
Add landing page for video documentation to user docs

### PR DESCRIPTION
**Pull request by manez**
**GitHub Issue**: #1487 

# What does this Pull Request do?

Adds a new page and corresponding entry in mkdocs.yml for an annotated and organized list of video documentation from Islandora Quick Lessons. 

# How should this be tested?

Preview & review. Please check links, read for typos, etc.

# Additional Notes:
The video docs already point back to the written documentation. This is to help make it easier to discover the videos from the main docs.

# Interested parties
@Islandora/8-x-committers

### CODE REVIEW

**Comment by manez** [comment]
Travis CI is a butthead.

**Comment by whikloj** [comment]
Actual error seems to be that you can't have a link from a document to a non-existant document.
https://travis-ci.com/github/Islandora/documentation/builds/165290402#L335

**Comment by manez** [comment]
Huh. One of the "inactive" pages.  I guess "storing" those in a directory in the docs folder isn't going to work.

**Comment by manez** [comment]
I tossed in a new issue to discuss what to do with the contents of that directory: https://github.com/Islandora/documentation/issues/1508

**Comment by manez** [comment]
Any @Islandora/8-x-committers in a merging mood? I've got some one who'd like to use this page. I can link to my fork, but it's so much prettier in the built docs 😄

**Review by mjordan — APPROVED** [review]
Looks good to me.

**Pull request merged**
