### PR TITLE
Create homepage.md

### LINKED ISSUE #1787: Welcome message on new site
I just spun up a new Playbook (Drupal 9.2.0-dev) and upon visiting the resulting Drupal site for the first time was greeted with this:

Welcome to Islandora 8 Islandora 8

This is not a node, it's static text in`web/core/themes/olivero/templates/includes/get-started.html.twig`. 

This is very friendly, but it's about Drupal, not Islandora. I know Islandora 8/9 is all about "getting off the island" but I wonder if having an Islandora-specific page that replaces this one would enhance the evaluator (or newbie) experience.

### PR DESCRIPTION
**Pull request by DonRichards**
## Purpose / why
Docs on how to update homepage based on new changes to islandora/islandora

## What changes were made?
Added a new MD file

## Verification
Review Changes are accurate based on pull request.

## Interested Parties
Pending Pull Request

* [ ] Does this PR link to related [issues](https://github.com/Islandora/documentation/issues/)?
* [ ] Does the proposed documentation align with the [Islandora Documentation Style Guide](https://islandora.github.io/documentation/contributing/docs_style_guide/)?
* [ ] Are the changes accurate, useful, free of typos, etc?
* [ ] Does this PR update the _last updated on_ date on the documentation page?

> __Person merging__ should ensure the following
* [ ] Does mkdocs still build successfully? (This is indicated by TravisCI passing. To test locally, and see warnings, see [How To Build Documentation](https://islandora.github.io/documentation/technical-documentation/docs-build/).)
* [ ] If pages are renamed or removed, have all internal links to those pages been fixed?
* [ ] If pages are added, have they been linked to or placed in the menu?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

### CODE REVIEW

**Comment by DonRichards** [comment]
Related Pull Request https://github.com/Islandora/islandora/pull/856

**Comment by mjordan** [comment]
@DonRichards what's the best way to test this?

**Comment by DonRichards** [comment]
@mjordan This is the docs related to this PR https://github.com/Islandora/islandora/pull/856

This PR needs to go in first for this to be relevant. But basically to test this is to follow the instructions provided by the MD file against the changes made in the [pull/856](https://github.com/Islandora/islandora/pull/856)

**Comment by mjordan** [comment]
@DonRichards thanks. If this needs to be reviewed by the end of the sprint, it's probably best to have someone who can commit to that timeline to review it. All of my dev/testing time is going into Workbench lately and I can't even keep to my promised timelines on that.

**Pull request closed without merging**
