### PR TITLE
Update users.md

### PR DESCRIPTION
**Pull request by manez**
## Purpose / why

Bringing the last of the existing How-To docs into line with the new GoodDocs based template.

## What changes were made?

New _Overview_ and _Before you start_ sections

## Verification

Review the text for typos and sense. There's some new markdown formatting here, so doing a [build](https://islandora.github.io/documentation/technical-documentation/docs-build/) wouldn't hurt, but I can confirm it looks when when I built it locally.

## Interested Parties

Any interested member of this org can review and merge this :)

Perhaps @ysuarez or @eldonquijote ?

---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Does this PR link to related [issues](https://github.com/Islandora/documentation/issues/)?
* [ ] Does the proposed documentation align with the [Islandora Documentation Style Guide](https://islandora.github.io/documentation/contributing/docs_style_guide/)?
* [ ] Are the changes accurate, useful, free of typos, etc?

> __Person merging__ should ensure the following
* [ ] Does mkdocs still build successfully? (This is indicated by TravisCI passing. To test locally, and see warnings, see [How To Build Documentation](https://islandora.github.io/documentation/technical-documentation/docs-build/).)
* [ ] If pages are renamed or removed, have all internal links to those pages been fixed?
* [ ] If pages are added, have they been linked to or placed in the menu?
* [ ] Did the PR receive at least one approval from a committer, and all issues raised have been addressed?

### CODE REVIEW

**Comment by eldonquijote** [comment]
Should we rename the menu entry in mkdocs.yml as part of this PR (currently 'Add a New User')? The page covers more than just adding a user, so perhaps we can call it 'Managing users'?

**Comment by manez** [comment]
@eldonquijote good point. Right now it's in a "How-To" section, so its title, and the titles of the other three How-To style pages, are all formatted as the answer to "How-To" (**How to** Create a user, **How to** Create or Update a View). Maybe "How to manage Users"  ? 

For now, anyway, since they could all get split up and moved around when we restructure docs.

**Comment by manez** [comment]
I went with "Create and Manage User Accounts"

**Review by eldonquijote — APPROVED** [review]

**Comment by manez** [comment]
@eldonquijote are you ok merging this?

**Pull request merged**
